name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v4.2.2
    
      - name: List repository files
        run: |
          echo "O repositório ${{ github.repository }} contém os seguintes arquivos:"
          tree
